###############################################################################################################
## 05_aggregate_for_cube.r
## Amelia Bertozzi-Villa
## Samir Bhatt
## October 2019
## 
## Collect "prop_no_nets" and "mean_net_count" parameters for each country to go into stock and flow.
## At the moment, make this a direct parallel in format, etc to the files generated by Sam
##############################################################################################################

aggregate_indicators <- function(reference_dir){
  
  ### Prep  #####----------------------------------------------------------------------------------------------------------------------------------
  
  countries <- gsub("([A-Z]{3})_all_output\\.RData", "\\1", list.files(reference_dir)[list.files(reference_dir) %like% ".RData"])
  start_year <- 2000

  ### Country Loop  #####----------------------------------------------------------------------------------------------------------------------------------
  
  indicator_list <- lapply(countries, function(this_country){
    print(paste("Collecting output for", this_country))
    
    new_fname <- file.path(reference_dir, paste0(this_country, "_all_output.RData"))
    load(new_fname)
    
    prop_no_nets <- model_estimates$nonet_prop_est
    mean_nets <- model_estimates$mean_net_count_est
    
    combined <- array(c(prop_no_nets, mean_nets) , dim=c(nrow(mean_nets), ncol(mean_nets), 2))
    rownames(combined) <- seq(start_year, (start_year+nrow(mean_nets)/4-0.25), 0.25)
    colnames(combined) <- 1:ncol(mean_nets)
    return(combined)
  })

  names(indicator_list) <- countries
  save(indicator_list, file=file.path(reference_dir, "net_probs_and_means.rData"))
  
} 

# dsub --provider google-v2 --project map-special-0001 --boot-disk-size 50 --image gcr.io/map-special-0001/map_rocker_jars:4-3-0 --regions europe-west1 --label "type=itn_stockflow" --machine-type n1-standard-4 --logging gs://map_users/amelia/itn/stock_and_flow/logs --input-recursive reference_dir=gs://map_users/amelia/itn/stock_and_flow/results/20191020_truncate_noise_dist CODE=gs://map_users/amelia/itn/code/stock_and_flow/ --output-recursive reference_dir=gs://map_users/amelia/itn/stock_and_flow/results/20191020_truncate_noise_dist --command 'cd ${CODE}; Rscript 05_aggregate_for_cube.r'
package_load <- function(package_list){
  # package installation/loading
  new_packages <- package_list[!(package_list %in% installed.packages()[,"Package"])]
  if(length(new_packages)) install.packages(new_packages)
  lapply(package_list, library, character.only=T)
}

package_load(c("data.table","rjags", "zoo", "ggplot2", "gridExtra"))
theme_set(theme_minimal(base_size = 12))

if(Sys.getenv("reference_dir")=="") {
  reference_dir <- "/Volumes/GoogleDrive/My Drive/stock_and_flow/results/20191009_stationary_sigm_loss"
  
} else {
  reference_dir <- Sys.getenv("reference_dir") 
}


aggregate_indicators(reference_dir)



